### ISSUE TITLE
Blank Screen after deviceReady

### ISSUE THREAD

**Issue by rajeevkannav** [FredrikSandell/ionic-hot-code-push#1]
We're following all instructions and getting blanks screen at android device

**Comment by Taewa** [comment]
@rajeevkannav I tested with iOS.

I had blank screen too, but as soon as I fixed ip properly in client/www/index.html, it worked.

I had another problem with build an app.
Seems because of old plugin?!
I just execute `ionic state reset` and resolved problem.
